apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-efficiency-auditor.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ include "k8s-efficiency-auditor.name" . }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}